name: Deploy Cassanova Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK
        run: yarn global add aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'us-east-1'

      - name: Install backend dependencies
        run: yarn install --frozen-lockfile

      - name: Build backend application
        run: yarn build

      - name: Deploy CDK stack
        run: |
          cd iac;
          yarn install --frozen-lockfile;
          cdk deploy --require-approval=never;
        env:
          CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_NUMBER }}
          CDK_DEFAULT_REGION: 'us-east-1'
          AWS_CLUSTER_ARN: ${{ vars.AWS_CLUSTER_ARN }}
          AWS_DEFAULT_SG: ${{ vars.AWS_DEFAULT_SG }}
          AWS_VPC_ID: ${{ vars.AWS_VPC_ID }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Deployment complete
        run: echo "âœ… Backend deployed successfully"